# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-21 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_dataset_dnaregion_domain_envsamplesource_has_ns_ill_dna_region_illuminaadaptor_illuminaadaptorref_il'),
    ]

    operations = [
        migrations.CreateModel(
            name='VampsAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, unique=True)),
                ('passwd', models.CharField(max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.IntegerField()),
                ('security_level', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=64)),
                ('institution', models.CharField(blank=True, max_length=128, null=True)),
                ('date_added', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'vamps_auth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VampsSubmissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_code', models.CharField(max_length=40, unique=True)),
                ('temp_project', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=132)),
                ('project_description', models.CharField(max_length=255)),
                ('funding', models.CharField(max_length=64)),
                ('num_of_tubes', models.SmallIntegerField()),
                ('date_initial', models.DateField()),
                ('date_updated', models.DateField()),
                ('locked', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vamps_submissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VampsSubmissionsTubes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_code', models.CharField(max_length=40)),
                ('tube_number', models.IntegerField()),
                ('tube_label', models.CharField(max_length=20)),
                ('dataset_description', models.CharField(max_length=100)),
                ('duplicate', models.CharField(max_length=5)),
                ('domain', models.CharField(blank=True, max_length=8, null=True)),
                ('primer_suite', models.CharField(max_length=60)),
                ('dna_region', models.CharField(max_length=40)),
                ('project_name', models.CharField(max_length=64)),
                ('dataset_name', models.CharField(max_length=64)),
                ('runkey', models.CharField(max_length=25)),
                ('barcode', models.CharField(max_length=10)),
                ('pool', models.CharField(max_length=30)),
                ('lane', models.CharField(max_length=5)),
                ('direction', models.CharField(max_length=5)),
                ('platform', models.CharField(max_length=15)),
                ('op_amp', models.CharField(max_length=5)),
                ('op_seq', models.CharField(max_length=5)),
                ('op_empcr', models.CharField(max_length=5)),
                ('enzyme', models.CharField(max_length=10)),
                ('rundate', models.CharField(max_length=10)),
                ('adaptor', models.CharField(max_length=3)),
                ('date_initial', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('on_vamps', models.CharField(max_length=10)),
                ('sample_received', models.CharField(max_length=15)),
                ('concentration', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quant_method', models.CharField(max_length=15)),
                ('overlap', models.CharField(choices=[('complete', 'complete'), ('partial', 'partial'), ('none', 'none')], max_length=8)),
                ('insert_size', models.IntegerField()),
                ('barcode_index', models.CharField(blank=True, max_length=12, null=True)),
                ('read_length', models.SmallIntegerField(blank=True, null=True)),
                ('trim_distal', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'vamps_submissions_tubes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewEnvSampleSource',
            fields=[
                ('env_sample_source_id', models.IntegerField(primary_key=True, serialize=False)),
                ('env_source_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'new_env_sample_source',
            },
        ),
    ]
