# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-10-16 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_db_name_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_vamps2',
            fields=[
                ('project_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('project_description', models.CharField(max_length=255)),
                ('rev_project_name', models.CharField(max_length=32, unique=True)),
                ('funding', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User_vamps2',
            fields=[
                ('user_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=64)),
                ('institution', models.CharField(blank=True, max_length=128, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.IntegerField()),
                ('security_level', models.IntegerField(blank=True, null=True)),
                ('encrypted_password', models.CharField(max_length=50)),
                ('sign_in_count', models.IntegerField()),
                ('current_sign_in_at', models.TimeField()),
                ('last_sign_in_at', models.TimeField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
            managers=[
                ('cache_all_method', django.db.models.manager.Manager()),
            ],
        ),
    ]
